export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ALL_COUNTRIES_FETCH_REQUESTED = 'ALL_COUNTRIES_FETCH_REQUESTED';
export const ALL_COUNTRIES_FETCH_SUCCEEDED = 'ALL_COUNTRIES_FETCH_SUCCEEDED';
export const SINGLE_COUNTRY_REQUEST = 'SINGLE_COUNTRY_REQUEST';
export const SINGLE_COUNTRY_SUCCEEDED = 'SINGLE_COUNTRY_SUCCEEDED';
export const CHANGE_SEARCH_FIELD_INPUT = 'CHANGE_SEARCH_FIELD_INPUT';
export const SET_ACTIVE_COUNTRY_LI = 'SET_ACTIVE_COUNTRY_LI';