export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SINGLE_COUNTRY_FETCH_START = 'SINGLE_COUNTRY_FETCH_START';
export const SINGLE_COUNTRY_FETCH_SUCCEEDED = 'SINGLE_COUNTRY_FETCH_SUCCEEDED';
export const SINGLE_COUNTRY_FETCH_FAILED = 'SINGLE_COUNTRY_FETCH_FAILED';

export const SEARCH_COUNTRIES_INIT = 'SEARCH_COUNTRIES_INIT';
export const SEARCH_COUNTRIES_FETCH_START = 'SEARCH_COUNTRIES_FETCH_START';
export const SEARCH_COUNTRIES_FETCH_SUCCEEDED = 'SEARCH_COUNTRIES_FETCH_SUCCEEDED';
export const SEARCH_COUNTRIES_FETCH_FAILED = 'SEARCH_COUNTRIES_FETCH_FAILED';
