export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';

export const SINGLE_COUNTRY_FETCH_START = 'SINGLE_COUNTRY_FETCH_START';
export const SINGLE_COUNTRY_FETCH_SUCCEEDED = 'SINGLE_COUNTRY_FETCH_SUCCEEDED';
export const SINGLE_COUNTRY_FETCH_FAILED = 'SINGLE_COUNTRY_FETCH_FAILED';
